name: CI

on:
  push:
    branches:
      - main  # branch que vai ser monitorarada

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt  # Ou o comando que você usa para instalar suas dependências
        
    - name: Linting
      run: |
        pre-commit run --all-files  # Execute pre-commit checks
        
    - name: Run tests
      run: |
        pytest -v
    
#    - name: Train ML model
#      run: |
#        kedro run

