model_options:
  test_size: 0.2
  random_state: 3
  n_iter: 30
  scoring: "roc_auc"
  
  grid_names: [
    "xgboost",
    "lightgbm",
    "random_forest",
    "logistic_regression",
    "support_vector"
  ]